Favorite words
sakhatyla/SakhaTyla.Mobile pull request #12
Opened 2023-01-31 20:38 UTC by tegorov

#7

2023-02-05 01:32 UTC, bacr requested changes

2023-02-05 01:32 UTC, bacr commented on lib/favorite/favorite_list.dart
> +                    child: Text('Кураанах')
Язык по-умолчанию русский, якутский надо добавить как перевод отдельной задачей.

2023-02-05 01:32 UTC, bacr commented on lib/favorite/favorite_list.dart
> +  final AppDatabase _database = locator<AppDatabase>();
получение данных нужно реализовать через Bloc

2023-02-05 01:32 UTC, bacr commented on lib/widgets/article_card.dart
> +  final AppDatabase _database = locator<AppDatabase>();
Обращение к данным делать через Bloc

2023-02-05 01:32 UTC, bacr commented on lib/main.dart
> +                onItemTapped: _onItemTapped
А зачем это нужно передавать в Bloc?

2023-02-17 02:28 UTC, tegorov commented on lib/favorite/favorite_list.dart
> +                    child: Text('Кураанах')
Исправил

2023-02-17 06:45 UTC, tegorov commented on lib/favorite/favorite_list.dart
> +  final AppDatabase _database = locator<AppDatabase>();
Исправил

2023-02-18 15:34 UTC, tegorov commented on lib/widgets/article_card.dart
> +  final AppDatabase _database = locator<AppDatabase>();
Добавил

2023-02-18 15:36 UTC, tegorov commented on lib/main.dart
> +                onItemTapped: _onItemTapped
Чтобы переводить на экран поиска с экрана "Избранное", например, когда пользователь нажимает на текст внутри карточки для поиска слова

2023-02-19 07:45 UTC, bacr commented
1. Думаю добавлять bloc для каждой статьи это лишнее, я скорее имел в виду использовать FavoriteBloc
2. Передавать в HomeBloc детали UI неправильно, надо подумать как сделать по другому
Попробую поправить это сам.

2023-02-19 07:49 UTC, bacr approved these changes

2023-02-19 07:50 UTC, merged