Добавил историю поиска
sakhatyla/SakhaTyla.Mobile pull request #6
Opened 2021-12-04 20:29 UTC by tegorov

Сохраняются последние 10 поисков

![Screenshot_1638647082](https://user-images.githubusercontent.com/42921436/144723684-8e2016a3-e143-4d7c-8c3b-b8634f441b9d.png)

2022-02-08 01:03 UTC, bacr requested changes
Когда выбираешь слово из списка подсказок, оно тоже должно добавляться в историю

2022-02-08 01:05 UTC, bacr requested changes
История должна показываться не только с главной страницы, но с любой страницы, где есть строка поиска.

2022-03-29 02:18 UTC, tegorov commented
> Когда выбираешь слово из списка подсказок, оно тоже должно добавляться в историю

 Добавил

2022-03-29 02:23 UTC, tegorov commented
> История должна показываться не только с главной страницы, но с любой страницы, где есть строка поиска.

Сейчас история показывается при нажатии на строку поиска. Пока сейчас у нас только один экран.

2022-04-11 04:41 UTC, bacr commented
> > История должна показываться не только с главной страницы, но с любой страницы, где есть строка поиска.
> 
> Сейчас история показывается при нажатии на строку поиска и пока у нас только один экран.

Есть главный экран, где отображается случайная статья, и экран со списком статей. Когда нажимаешь на строку поиска на экране со списком статей, тоже должен открываться список с историей.

Кроме того, когда нажимаешь на крестик, строка поиска должна очищаться, а сейчас этого не происходит.

2022-09-15 10:17 UTC, merged